server:
  port: 9876
spring:
  cache:
    type: CAFFEINE
#    caffeine: 
#      spec: maximumSize=500,expireAfterWrite=600s
      
  http:
    encoding:
      charset: utf-8
  jpa:
    database: MYSQL
    show-sql: true
      
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jsp153?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: weixing
    
mybatis:
  mapper-locations:
  - classpath:mapper/**/*.xml #mapper映射文件